//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RylPacketAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TesteRel
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Id_Teste { get; set; }
        public string Name { get; set; }
    
        public virtual Teste Teste { get; set; }
    }
}
