//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RylPacketAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teste
    {
        public Teste()
        {
            this.TesteRel = new HashSet<TesteRel>();
        }
    
        public System.Guid ID { get; set; }
        public string Nome { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual ICollection<TesteRel> TesteRel { get; set; }
    }
}
